spring:
    application:
        name: springcloud-producer-hystrix

server:
    port: 8101

#eureka配置
eureka:
    instance:
        #服务名称修改
        instance-id: springcloud-producer-hystrix
        #访问路径可以显示ip地址
        prefer-ip-address: true
    client:
        #表示是否将自己注册进eureka  默认为true
        register-with-eureka: true
        #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
        fetch-registry: true
        service-url:
            #单机配置
            defaultZone: http://localeureka01.com:8000/eureka,http://localeureka02.com:8001/eureka
