server:
  port: 8000
eureka:
  instance:
    hostname: localeureka.com
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false       #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://localeureka.com:8000/eureka/


